# Form implementation generated from reading ui file '.\TempoSphere.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(452, 242)
        MainWindow.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.changeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.changeButton.setGeometry(QtCore.QRect(20, 90, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(12)
        self.changeButton.setFont(font)
        self.changeButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 0, 255);\n"
"border-radius: 12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 170, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 0, 127);\n"
"}\n"
"S")
        self.changeButton.setObjectName("changeButton")
        self.Clock = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Clock.setGeometry(QtCore.QRect(20, 160, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(12)
        self.Clock.setFont(font)
        self.Clock.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 0, 255);\n"
"border-radius: 12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 170, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(255, 0, 127);\n"
"}\n"
"")
        self.Clock.setObjectName("Clock")
        self.lcdNumber = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(230, 110, 181, 71))
        self.lcdNumber.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.lcdNumber.setObjectName("lcdNumber")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 0, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 10, 71, 61))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\tomate.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 0, 71, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(".\\reloj.png"))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 452, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.changeButton.setText(_translate("MainWindow", "Pomodoro timer"))
        self.Clock.setText(_translate("MainWindow", "Clock"))
        self.label.setText(_translate("MainWindow", "TempoSphere"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
